# Generated by Django 3.0 on 2020-01-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='room_name',
        ),
    ]
