# Generated by Django 3.0 on 2020-01-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room R', max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(default="No Room description'", max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='down',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='left',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='right',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='up',
            field=models.IntegerField(default=None),
        ),
    ]
