# Generated by Django 3.0 on 2020-01-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='Item Description', max_length=256),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room f', max_length=64),
        ),
    ]
