# Generated by Django 3.0 on 2020-01-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0002_auto_20200107_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room w', max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='down',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='left',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='right',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='up',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
