# Generated by Django 3.0 on 2020-01-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0002_auto_20200109_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_name', models.CharField(max_length=64)),
                ('roomID', models.IntegerField(default=86)),
                ('hp', models.IntegerField(default=1)),
                ('strength', models.IntegerField(default=3)),
                ('description', models.CharField(default='enemy description', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='strength',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room u', max_length=64),
        ),
    ]
