# Generated by Django 3.0 on 2020-01-10 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0002_auto_20200109_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room X', max_length=64),
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_name', models.CharField(max_length=64)),
                ('hp', models.IntegerField(default=8)),
                ('strength', models.IntegerField(default=5)),
                ('description', models.CharField(default='enemy description', max_length=500)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tower_app.Room')),
            ],
        ),
    ]
