# Generated by Django 3.0 on 2020-01-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0002_auto_20200109_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room R', max_length=64),
        ),
    ]
