# Generated by Django 3.0.2 on 2020-01-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0002_auto_20200109_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room J', max_length=64),
        ),
    ]
