# Generated by Django 3.0 on 2020-01-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0003_auto_20200109_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='location',
        ),
        migrations.AddField(
            model_name='enemy',
            name='roomID',
            field=models.IntegerField(default=29),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='hp',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='strength',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room T', max_length=64),
        ),
    ]
