# Generated by Django 3.0 on 2020-01-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0004_auto_20200108_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room A', max_length=64),
        ),
    ]
