# Generated by Django 3.0 on 2020-01-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0005_auto_20200110_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='hp',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='roomID',
            field=models.IntegerField(default=41),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='strength',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room D', max_length=64),
        ),
    ]
