# Generated by Django 3.0 on 2020-01-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0005_auto_20200110_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='strength',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='hp',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='roomID',
            field=models.IntegerField(default=105),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='strength',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room p', max_length=64),
        ),
    ]
