# Generated by Django 3.0 on 2020-01-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0006_auto_20200108_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='playerID',
        ),
        migrations.AddField(
            model_name='inventory',
            name='player',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='tower_app.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room S', max_length=64),
        ),
    ]
