# Generated by Django 3.0 on 2020-01-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0007_auto_20200108_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tower_app.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room z', max_length=64),
        ),
    ]
