# Generated by Django 3.0 on 2020-01-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0007_auto_20200110_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='hp',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='roomID',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='strength',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room s', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='strength',
            field=models.IntegerField(default=26),
        ),
    ]
