# Generated by Django 3.0 on 2020-01-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0008_auto_20200108_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='playerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tower_app.Player'),
        ),
        migrations.AddField(
            model_name='item',
            name='roomID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tower_app.Room'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room G', max_length=64),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
