# Generated by Django 3.0 on 2020-01-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0009_auto_20200108_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room k', max_length=64),
        ),
    ]
