# Generated by Django 3.0 on 2020-01-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0010_auto_20200108_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='playerID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='roomID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room c', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tower_app.Room'),
        ),
    ]
