# Generated by Django 3.0 on 2020-01-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0011_auto_20200108_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='strength',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room r', max_length=64),
        ),
    ]
