# Generated by Django 3.0 on 2020-01-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0012_auto_20200108_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(default='weapon', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='roomID',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room Q', max_length=64),
        ),
    ]
