# Generated by Django 3.0 on 2020-01-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0013_auto_20200108_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='playerID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='roomID',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room n', max_length=64),
        ),
    ]
