# Generated by Django 3.0 on 2020-01-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_app', '0014_auto_20200108_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Room G', max_length=64),
        ),
    ]
